#!/bin/bash


# on transfrome les donnees pour les mettre en fonction de c puis comme il faut pour trust 

traite()
{
file=$1
NR=`awk 'END {printf("%s ",NR)}' $file`
echo 1 $NR
awk '{printf("%s ",$1) } END {printf("\n")}'  $file
echo 1 $NR $NR
awk '{printf("%s ",$2)} END {printf("\n")}'  $file
}
traite lnACell.txt > lnA.txt
traite Eacell_fAlpha.txt > Ea.txt


sed "s?test_Ea?Ea?g;s?test_lnA?lnA?g" EF_s.data > EF.data


sed "s/EF/VEFPreP1B/" EF.data > VEF.data
sed "s?kb?test_relaxation kb?g" VEF.data > VEF_relax.data
sed "s?t_max 0.1e-0?t_max 0.1e-1?" VEF.data > VEF_0.01.data
python $TRUST_ROOT/bin/KSH/preprocessor.py Emballement.prm.P Emballement.prm


sed "s/transformer dom x-0.05 y-0.05/transformer dom x-0.05 y-0.05 extruder_en3  {  domaine  1 dom nb_tranches 2    direction 0 0 1e-2  } RegroupeBord dom bound { bound devant derriere }/;s/Pb_Conduction_Concentration pb/Pb_Conduction_Concentration pb  dimension 3/; s/segment 80 -0.05 0 0.05 0/segment 80 -0.05 0 5e-3   0.05 0 5e-3/" VEF.data > VEF_3D.data


